### PR TITLE
Test for 2021.1

### PR DESCRIPTION
**Pull request by nvdaes**
## Link to issue number:
None
### Summary of the issue:
Review to release a version compatible with NVDA 2021.1
### Description of how this pull request fixes the issue:
Tweaks and some annotations
### Testing performed:
Lint with flake8
### Known issues with pull request:
None
### Change log entry:
- Compatible with NVDA 2021.1

### CODE REVIEW

**Comment by nvdaes** [comment]
@grisov, if you can, would you help me with mypy. This raises errors and the same locally using tox.
Have a nice day

**Comment by grisov** [comment]
Hi Noelia,

MyPy found issues in add-on files.

May I edit them and create a PR to approve the changes?

Cheers :)

**Comment by nvdaes** [comment]
Hello, where are issues found in add-on files? I think you can create a PR :) See you soon there, in add-on files, with other add-ons.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Thanks! I think that type hints are just needed for functions not
directly known by NVDA, for example, not needed for scripts or
makeSettings and so on. But if you think that more type hints are
defined let me know.



See you soon!

2021-05-27 20:11 GMT+02:00, Oleksandr Gryshchenko ***@***.***>:

**Comment by nvdaes** [comment]
Let's close this in favour of #32

**Pull request closed without merging**
